In [30]:
from keras.models import load_model
import os
from keras.models import Model
from keras.preprocessing import image as image_utils
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix
from google.colab import drive
drive.mount('/content/drive')
model = load_model('/content/drive/My Drive/Colab Works/gestmodelLS.h5')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
gestures = {'L': 'Like',
           'fist': 'Caged',
           'C': 'C',
           'okay': 'Nice',
           'peace': 'Peace',
           'palm': 'Blessings',
            '0': 'Circle',
            '1': 'Released',
            '4': 'Four',
            'g': 'You',
            'i': 'I',
            'x': 'Bird',
            'y': 'Call',
            '7': 'Super',
            'q': 'Little',
            'r': 'Joined'
            }

gestures_map = {'Caged' : 0,
                'Like': 1,
                'Nice': 2,
                'Blessings': 3,
                'Peace': 4,
                'C': 5 ,
                'Circle': 6,
                'Released': 7,
                'Four': 8,
                'You': 9,
                'I': 10,
                'Bird':11,
                'Call':12,
                'Super':13,
                'Little':14,
                'Joined':15
                }

In [0]:
gesture_names = {0: 'Caged',
                 1: 'Like',
                 2: 'Nice',
                 3: 'Blessings',
                 4: 'Peace',
                 5: 'Z',
                 6: 'Circles',
                 7: 'Released',
                 8: 'Four',
                 9: 'You',
                 10: 'I',
                 11: 'Birds',
                 12: 'Calls',
                 13: 'Super',
                 14: 'Little',
                 15: 'Joined'}
def get_classification_metrics(X_test, y_test):
    pred = model.predict(X_test)
    pred = np.argmax(pred, axis=1)
    y_true = np.argmax(y_test, axis=1)
    gesture = ""
    for ges in y_true:
      gesture += gesture_names[ges] + " "
    print(confusion_matrix(y_true, pred))
    print('\n')
    print(classification_report(y_true, pred))
    return gesture,pred


In [0]:
def process_image(path):
  try:
    img = cv2.imread(path)
    img =  cv2.resize(img, (224, 224), interpolation = cv2.INTER_AREA)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = np.array(img)
    return img
  except Exception as e:
    print(str(e))

def process_data(X_data, y_data):
    X_data = np.array(X_data, dtype = 'float32')
    if rgb:
        pass
    else:
        X_data = np.stack((X_data,)*3, axis=-1)
    X_data /= 255
    y_data = np.array(y_data)
    y_data = to_categorical(y_data)
    return X_data, y_data

In [35]:
f = open("/content/drive/My Drive/Colab Works/Input.txt","r")
Lines = f.readlines() 
f.close()
X_test = []
y_test = []
rgb = False
for line in Lines: 
    images=line.strip().split(',')
    for image in images:
        path = "/content/drive/My Drive/Colab Works/Testing"
        path = os.path.join(path,image)
        if(path != "/content/drive/My Drive/Colab Works/Testing/"): 
          X_test.append(process_image(path))
          y_test.append(gestures_map[gestures[image.split('_')[0]]])

X_test,y_test = process_data(X_test, y_test)
gesture,pred = get_classification_metrics(X_test, y_test)
of = open("/content/drive/My Drive/Colab Works/Output.txt","w")
of.close()
for pre in pred:
      of = open("/content/drive/My Drive/Colab Works/Output.txt","a+")
      word = gesture_names[pre]
      if "Z" in word:
        of.write("\n")
        of.close()
      else:
        of.write(word+" ")
        of.close()
f = open("/content/drive/My Drive/Colab Works/Output.txt","r")
Lines = f.readlines()
f.close()
ac_ges = gesture.split("Z")
for i in range(len(Lines)):
  print("Actual Continuous Sign Gesture:",ac_ges[i])
  print("Predicted Continuous Sign Gesture:",Lines[i])



[[ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
      